### PR TITLE
MCR-XXXX Update sprites and use new icon for unlockables

### PR DESCRIPTION
**Pull request by jasonlwj**
Mainly just the icons in the menu/overlay. Also some of the factions as well. Didn't really touch the units and tiles on the board (might get to it later though)

### CODE REVIEW

**Comment by jasonlwj** [comment]
image

**Comment by jasonlwj** [comment]
image

**Comment by ChrisNeedham24** [comment]
This man is simply built different

**Comment by jasonlwj** [comment]
🙏

**Comment by ChrisNeedham24** [comment]
Couple of things at a glance:
- Need to merge main in.
- It looks like you've got a newer version of Pyxel than what's defined in the requirements.txt, so you can either rollback your version (but that may mean that you need to re-do your changes - not fun), or update the requirements version to yours, but there have been changes to the display sizing in the time between the versions, so you'll also need to add `display_scale=5` to the `pyxel.init()` call if you choose that. (Currently you can't actually run the game at all)
- All the icons look amazing, but I think the fortune one looks a bit too much like a health icon for my tastes, not sure how you'd alter it though.

**Comment by jasonlwj** [comment]
My reaction to that information: 
image

**Comment by jamesgiu** [comment]
I think you'll need to update the README with new screenshots of the new sprites in action 😂

**Comment by ChrisNeedham24** [comment]
> I think you'll need to update the README with new screenshots of the new sprites in action 😂

Yeah I mentioned that when we were at Belle's lol

**Comment by jasonlwj** [comment]
Regarding the fortune icon, I turned it into sort of a gem thingo
image

**Comment by jasonlwj** [comment]
>  you'll also need to add `display_scale=5` to the `pyxel.init()` call if you choose that.

Is this actually needed? I'm running the game on pyxel==1.9.0 and I can run the game fine

**Comment by ChrisNeedham24** [comment]
I don't mind the gem icon tbh, but my only problem is that a couple of the faction logos were based on the previous one, so they might look out of place now. Not sure, though.

For the display_scale thing, it doesn't stop the game from running but the default launch now displays the game much smaller. With the display_scale set to 5, I believe it looks the same as it did previously.

**Comment by jasonlwj** [comment]
Interesting. Without display_scale set, the game still launches at the same window size for my machine. Will add it though.

Regarding those faction symbols - I'm just throwing some ideas around atm:

The Godless
image

The Orthodox
image

The idea being that I'd keep the general shape of the new blessing icon.

**Comment by ChrisNeedham24** [comment]
So I can't seem to actually run the newer version of pyxel at all on my old laptop (obviously left my desktop at home) so I can't reproduce the display size difference. The fact that I can't run it at all probably also means I won't be able to merge this until next weekend unfortunately.

**Comment by ChrisNeedham24** [comment]
Alright I've reproduced the display size difference between versions 1.6.9 and 1.9.0 of Pyxel:
Screen Shot 2022-11-20 at 7 44 58 pm
Screen Shot 2022-11-20 at 7 45 32 pm

It's not a huge difference, but when you add `display_scale=5`, it makes it so the size doesn't change.

So there's just three things left for this one now:
* Adding `display_scale=5` to `pyxel.init()`
* Taking new screenshots for the README
* Changing the faction icons to what you've already suggested

**Review by ChrisNeedham24 — APPROVED** [review]
LGTM!

**Pull request merged**
