### PR TITLE
Handle cases where loaded save files are no longer valid #94

### PR DESCRIPTION
**Pull request by langstof825**
Ready for review. Added new popup for when loading a save file fails. Added exception handling for load_game function. Created MCR-103 for the backwards compatibility stuff.

### CODE REVIEW

**Comment by langstof825** [comment]
The linter seems to be failing as I am catching the general Exception. Is there a way to disable the lint for that specific try/except?

**Comment by ChrisNeedham24** [comment]
Well ideally we could have the catch as `except (AttributeError, OtherException):` but if you're not 100% on which different exceptions can be thrown, you should be able to chuck `# pylint: disable=broad-except` above the `except`.

**Comment by langstof825** [comment]
Yeah I wasn't 100% sure apart from AttributeError.

**Review by ChrisNeedham24 — CHANGES_REQUESTED** [review]
Actual warning and functionality works great! However, would it be possible to take the player back to the load game screen rather than the main menu when the save is corrupted/invalid?

**Review by ChrisNeedham24 — APPROVED** [review]
LGTM!

**Pull request merged**
